name: lucky_beast_card_template_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.3
  fluent_ui: ^4.10.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  image_gallery_saver: ^2.0.3
  slang: ^4.12.0
  slang_flutter: ^4.12.0
  provider: ^6.1.5+1
  equatable: ^2.0.8
  desktop_drop: ^0.7.0
  filepicker_windows: ^2.1.4
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.10.5
  slang_build_runner: ^4.12.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  fonts:
    - family:  MdiExtensionIcon
      fonts:
        - asset: assets/fonts/MdiExtensionIcon.ttf

  assets:
    - assets/logo.png
    - assets/offical_card_template/element_type/
    - assets/offical_card_template/construction_card/
    - assets/offical_card_template/minion_card/
    - assets/offical_card_template/spell_card/
    - assets/offical_card_template/rarity_type/
    #- assets/custom_card_template/

flutter_launcher_icons:
  #android: "launcher_icon"
  #ios: true
  #image_path: "assets/icon.png"
  #min_sdk_android: 21 # android min sdk min:16, default 21
  #web:
  #  generate: true
  #  image_path: "path/to/image.png"
  #  background_color: "#hexcode"
  #  theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  #macos:
  #  generate: true
  #  image_path: "path/to/image.png"
